[package]
name = "js-runtime"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = {git = "https://github.com/exerum/tokio", branch = "wasmer-wasm32-wasi", features = [ "rt", "net", "time" ] }
protocol = { git = "https://github.com/exerum/protocol" }
bincode = "1.3.3"

[dependencies.quickrs]
git = "https://github.com/exerum/quickrs"
default-features = false
version = "0.1.2"
features = ["exports", "loader", "futures", "tokio"]
branch = "master"

[patch.crates-io]
mio = { git = "https://github.com/exerum/mio", branch = "wasmer-wasm32-wasi-beta" }
tokio = { git = "https://github.com/exerum/tokio", branch = "wasmer-wasm32-wasi" }